/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terredimezzo;

import terredimezzo.Personaggi.razze.personaggirazza.Nani;
import terredimezzo.Personaggi.razze.personaggirazza.Sudroni;
import terredimezzo.Personaggi.Male;
import terredimezzo.Personaggi.razze.personaggirazza.Hobbit;
import terredimezzo.Personaggi.razze.personaggirazza.Orchi;
import terredimezzo.Personaggi.Eroi;
import terredimezzo.Personaggi.razze.personaggirazza.Urukhai;
import terredimezzo.Personaggi.Bene;
import terredimezzo.Personaggi.razze.personaggirazza.Elfi;
import terredimezzo.Personaggi.razze.personaggirazza.Uomini;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pizzarelli
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    
    DefaultListModel modelBene = new DefaultListModel();
    DefaultListModel modelMale = new DefaultListModel();
        
    Bene bene = new Bene();
    Male male = new Male();
    public frmMain() {
        initComponents();
        
        lstBene.setModel(modelBene);
        lstMale.setModel(modelMale);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBene = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMale = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSchieramenti = new javax.swing.JButton();
        btnCombatti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bene"));

        jScrollPane1.setViewportView(lstBene);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Male"));

        jScrollPane2.setViewportView(lstMale);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Terra di mezzo");

        jLabel2.setText("Come funziona il gioco?");

        jLabel3.setText("Bisogna creare uno schieramento per il bene e per il male");

        jLabel4.setText("Poi cliccare sul bottone \"Esegui\" per calcolare chi ha vinto");

        btnSchieramenti.setText("Crea Schieramenti");
        btnSchieramenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchieramentiActionPerformed(evt);
            }
        });

        btnCombatti.setText("Combatti");
        btnCombatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombattiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSchieramenti, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(btnCombatti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSchieramenti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCombatti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCombattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombattiActionPerformed

        if (bene.calcolaForza() == 0 & male.calcolaForza() == 0) {
            JOptionPane.showMessageDialog(null, "Prima di procedere crea uno schieramento");return;
        }
        if (bene.calcolaForza() > male.calcolaForza())
            JOptionPane.showMessageDialog(null, "Vince il bene con una forza di " + bene.calcolaForza() + " contro il male che ha una forza di " + male.calcolaForza());
        else
            JOptionPane.showMessageDialog(null, "Vince il male con una forza di" + male.calcolaForza() + " contro il bene cha ha una forza di " + bene.calcolaForza());
    }//GEN-LAST:event_btnCombattiActionPerformed

    private void btnSchieramentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchieramentiActionPerformed
        int i;

        bene.clear();
        male.clear();
        modelBene.clear();
        modelMale.clear();
        
        for (i = 0; i < 3; i++) {
            Uomini r = new Uomini();
            bene.addPersonaggi(r);
            modelBene.addElement("Uomo - Forza: " + r.forza());
        }
        for (i = 0; i < 3; i++) {
            Elfi r = new Elfi();
            bene.addPersonaggi(r);
            modelBene.addElement("Elfo - Forza: " + r.forza());
        }
        for (i = 0; i < 3; i++) {
            Nani r = new Nani();
            bene.addPersonaggi(r);
            modelBene.addElement("Nano - Forza: " + r.forza());
        }
        for (i = 0; i < 3; i++) {
            Hobbit r = new Hobbit();
            bene.addPersonaggi(r);
            modelBene.addElement("Hobbit - Forza: " + r.forza());
        }

        Eroi eB = new Eroi();
        bene.addPersonaggi(eB);
        modelBene.addElement("Eroe - Forza: " + eB.forza());
        for (i = 0; i < 4; i++) {
            Orchi r = new Orchi();
            male.addPersonaggi(r);
            modelMale.addElement("Orco - Forza: " + r.forza());
        }
        for (i = 0; i < 4; i++) {
            Urukhai r = new Urukhai();
            male.addPersonaggi(r);
            modelMale.addElement("Urukhai - Forza: " + r.forza());
        }
        for (i = 0; i < 4; i++) {
            Sudroni r = new Sudroni();
            male.addPersonaggi(r);
            modelMale.addElement("Sudrone - Forza: " + r.forza());
        }
        Eroi eM = new Eroi();
        male.addPersonaggi(eM);
        modelMale.addElement("Eroe - Forza: " + eM.forza());

    }//GEN-LAST:event_btnSchieramentiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombatti;
    private javax.swing.JButton btnSchieramenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstBene;
    private javax.swing.JList<String> lstMale;
    // End of variables declaration//GEN-END:variables
}
